### ISSUE TITLE
HB: "Jump to waypoint" feature only works on clicking text

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#108]
Example:
http://tm.teresco.org/hb/index.php?r=aut.b161
Move your mouse to the "L40" field. It's highlighted but clicking does not center the map to "L40" wp. It only works when clicking on the "L40" text itself but clicking on any other position of the field or the line does not work. It took some time till I got why it does not always work.........

Generally, it should work because it works in the HB for system selection: http://tm.teresco.org/hb/. The whole line does link to the desired system HB.

I think the whole line of the table in the waypoint browser should be linked.

btw: I don't see any reason when it should not be similar in the route browser: tm.teresco.org/hb/rg=AUT. Here, just the link in the last column can be clicked...

**Comment by theFXexpert** [comment]
Submitted code for the original issue. I'm not sure what is the desired behavior for the HB search table. What I mean is, right now you can choose whether or not to open a new tab or not. If the whole row is clickable using javascript, either it has to open a new tab or not; no choice is allowed by the user. I'm not going to touch it right now since I don't know how everyone is used to doing it.

**Comment by michihdeu** [comment]
> I'm not sure what is the desired behavior for the HB search table.
I think it's working fine.

**Comment by jteresco** [comment]
#116 is live on the site.  @michihdeu please close the issue if you're happy with the fix (submitted by @theFXexpert).  Thanks.

**Comment by michihdeu** [comment]
Working fine. Thanks 👍
