### ISSUE TITLE
HB: add direct link to connected routes

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#192]
Maybe at the top and bottom (as appropriate) of the waypoint table, have a link to the continuation of the next route in the connected route in an adjacent region.

**Comment by yakra** [comment]
This could function as a "fix" for situations where the border waypoints have mismatched coords.
Otherwise, the *Intersecting/Concurrent Routes* feature would be fine for this IMO.

**Comment by michihdeu** [comment]
> This could function as a "fix" for situations where the border waypoints have mismatched coords.

I hope we don't wanna implement the feature for situations like this. The NMP issue should be fixed. Period.

I guess @jteresco just wants to show the intersecting/concurrent routes link in the table too!?! Who has requested the feature, was it you?

I doubt that it's simple to find exactly the correct route though because there might be more than one... The feature might cause more trouble than being usefull... Just my 2c...

**Comment by jteresco** [comment]
It's not intended an an NMP workaround.  Just a more convenient way to switch from a route to its continuation in another region.  There would only be links at the start and the end, and only to continuation routes as specified in a _con.csv file, not based on coordinates.

**Comment by yakra** [comment]
Potential for complication:
https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/cantch_con.csv
> cantch;TCH;;(Main);bc.tchmai,ab.tchmai,sk.tchmai,mb.tchmai,**on.tchlak,on.tchnor,on.tchott**,qc.tchmai,nb.tchmai,ns.tchmai

In Ontario, we have a 3-pronged TCH (Main).
[forum thread](http://tm.teresco.org/forum/index.php?topic=130.msg613#msg613)

**Comment by michihdeu** [comment]
> Potential for complication:

Why? It's still the same system...

**Comment by yakra** [comment]
True, but should the feature be implemented, it should be robust enough to withstand and cope with being handed bad/buggy data.

**Comment by michihdeu** [comment]
With the intersecting routes link shown in the info box of the first and last waypoint, it is already possible to jump to the next route.

Do we want to place the option for connected routes more prominent on the HB?
OTOH, is jumping to the connected route really more important than jumping to any other route - the next route of one's travel?

Is there additional benefit or does it just overload the HB with information?

**Do we still need this feature?**

**Comment by yakra** [comment]
> With the intersecting routes link shown in the info box of the first and last waypoint, it is already possible to jump to the next route.

If and only if the next route has matching coordinates.
If coords mismatch at the border point on two adjacent chopped routes, then the Intersecting/concurrent routes feature is not enabled.

> Is there additional benefit

A user will be able to easily navigate to the prev/next connected route, even if the Intersecting/concurrent routes feature is broken.
I anticipate it'd be pretty common for a user traveling a multi-region route in one region to have traveled the same route in an adjacent region as well.

> or does it just overload the HB with information?

Not IMO. Links can unobtrusively be placed in small text above/below the Waypoints table.

> **Do we still need this feature?**

Yes.

**Comment by yakra** [comment]
> Sure, csv files must be correct. That's not a matter of this feature but of maintenance...

We wouldn't have to do anything special to fix the 3-pronged TCH other than fix the .csv.
Links can simply be to the prev/next chopped root in the ConnectedRoute's roots list; GIGO.

**Comment by yakra** [comment]
I think this feature would be more convenient than picking the proper connected route out of a long list.

> ### ESP/FRA
> **Waypoint 0**
> [Coords.:](http://www.openstreetmap.org/?lat=43.339904&lon=-1.752577) 43.339904°, -1.752577°
> Intersecting/Concurrent Routes:
> [FRA-NAQ E5](http://travelmapping.net/hb/?r=franaq.e5&lat=43.339919&lon=-1.752566&zoom=16)
> [ESP-PV E5 (San Sebastian)](http://travelmapping.net/hb/?r=esppv.e5&lat=43.339919&lon=-1.752566&zoom=16)
> [ESP-PV E70](http://travelmapping.net/hb/?r=esppv.e70&lat=43.339919&lon=-1.752566&zoom=16)
> [FRA-NAQ E70](http://travelmapping.net/hb/?r=franaq.e70&lat=43.339919&lon=-1.752566&zoom=16)
> [ESP-PV E80 (San Sebastian)](http://travelmapping.net/hb/?r=esppv.e80&lat=43.339919&lon=-1.752566&zoom=16)
> [ESP-PV AP1 (Bergara)](http://travelmapping.net/hb/?r=esppv.ap001&lat=43.339919&lon=-1.752566&zoom=16)
> [ESP-PV AP8](http://travelmapping.net/hb/?r=esppv.ap008&lat=43.339919&lon=-1.752566&zoom=16)
> [FRA-NAQ A63](http://travelmapping.net/hb/?r=franaq.a063&lat=43.339919&lon=-1.752566&zoom=16)

It may not be clear to all users that only one option in the popup is a connected route that can be used in a [Multi-region list file entry](https://github.com/TravelMapping/DataProcessing/issues/58).
Adding this feature could help reinforce the concept of what a connected route is. (Right now, the concept may be fairly opaque to most regular users...)

**Comment by yakra** [comment]
@jteresco wrote in the OP:
> Maybe at the top and bottom (as appropriate) of the waypoint table, have a link to the continuation of the next route in the connected route in an adjacent region.

Alternately, how about a drop-down box listing all chopped routes in the same connected route?

Or why not even both?

**Comment by michihdeu** [comment]
My previous crazy idea was rejected - which was pretty fine - but.... 😄 why not loading all routes at once? Just a button "show whole route" to extend from the region-specific route to the entire connected route. With the multi-region .list file entry and [this great idea](https://github.com/TravelMapping/Web/issues/421#issuecomment-636612618):

> * Instead, include in waypoints table and waypoint popups along with the label. This way each waypoint will have the text string that uniquely identifies it within a connected route.

It would be perfect! Simple UI and code (just one button required), userfriendly solution due to having everything at once.

**Comment by yakra** [comment]
I think it would be worthwhile to have both options. Both #192 and #421, that is.

Glad you like my idea :smile:, though I don't think it's quite that simple to code. Maybe on the HTML side, sure, but the PHP/SQL side of it is pretty hairy. Back in November I had a go at waypoints.js.php, and it got a little overwhelming pretty fast; a lot of moving parts. Gotta refamiliarize myself with both the code and my work on it -- Could be that I put it on the backburner on *"I don't get it!"* grounds, or it could be that it was just on *"OK, that's enough work for now; I'll come back to this later"* grounds.

A complicating factor is, code has changed since then, and @jteresco is [hoping to move more code away from waypoints.js.php](http://forum.travelmapping.net/index.php?topic=3647.msg18934#msg18934)...

This issue OTOH should be quicker & easier to implement (mostly html, with the new SQL query/queries smaller & more manageable) and more within (hopefully) my capabilities.

**Comment by yakra** [comment]
I wrote:
> We wouldn't have to do anything special to fix the 3-pronged TCH other than fix the .csv.

[O HAY that already happened 3 years ago LOL](https://github.com/TravelMapping/HighwayData/commit/aabfeea7cc85b14705322f09c93180247065da67)

**Comment by jteresco** [comment]
I am expecting that the new showroute (ready for testing soon) will meet the needs indicated here.
