### ISSUE TITLE
HB: Remove coordinates from waypoints table?

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#221]
Do we really need the coordinates in the waypoints table?
IMO it's just needless clutter, and removing them could help attain a cleaner appearance; having the coordinates listed in the InfoWindow is sufficient.
I think I did search for a string within that text  **once**, long enough back to not remember the circumstances.
That said though, I would not miss them if they were gone. I could just as easily have found the desired waypoint another way.

I'll [crosspost this to the forum](http://tm.teresco.org/forum/index.php?topic=2193) to seek opinions from a wider base of users...

**Comment by michihdeu** [comment]
> Do we really need the coordinates in the waypoints table?

No!

**Comment by yakra** [comment]
The following issues all fall under the design/layout/presentation umbrella, and should probably be considered concurrently:
#218 HB: Add user traveled length and percent
#221 HB: Remove coordinates from waypoints table?
#222 HB: cleaner info presentation, more CHM-style
#224 HB: Deprecated labels

**Comment by jteresco** [comment]
This one's easy enough if there's no outburst of opinions in favor of keeping it.

**Comment by jteresco** [comment]
I did a quick reorg of the HB layout, and put it on tmtest.  Please give it a look.

**Comment by michihdeu** [comment]
Thanks. Font and font size on top (too large) and left (too small) looks odd. Especially list name is too small and inconspicuous... Looks like an additional city name...

What do you think about an own table "Name" between "Stats"*  and "Waypoints"? The 2nd line "User list file name"?

*w/o "route" because all tables are about the route

**Comment by michihdeu** [comment]
There should be some pixel between the text on top and the map...

**Comment by jteresco** [comment]
Changed some sizes and fonts.

**Comment by michihdeu** [comment]
Looks better.

**Comment by michihdeu** [comment]
Just a thought... We wanna make the HB more intuitive so that (new) user find the requited info more easily.
If there would be a "copy icon" just next to the list file name and a "copy icon" on the info window just next to the waypoint name... Clicking on the icon, the name is copying the text to clipboard (and it can be paste to the user list file)...

**Comment by jteresco** [comment]
See #226

**Comment by michihdeu** [comment]
> See #226

That wasn't mentioned above but I like it, see http://tm.teresco.org/forum/index.php?topic=2018

Again, my latest suggestion with other words: I currently have to mark and copy the list file name. I thought that an icon could bring an user to click on it instead of typing the text into the list file... To avoid typos AND TO INDICATE THAT THIS TEXT IS NEEDED FOR THE LIST FILE ENTRY

I think the latter is what @yakra wrote in #222:

> A layout more similar to CHM's format, without the LIST Name hidden down in the Route Stats table, would be nicer looking and less confusing IMO.

**Comment by yakra** [comment]
![this is a test](http://tm.teresco.org/forum/index.php?action=dlattach;topic=2171.0;attach=130;image)
