### ISSUE TITLE
Datacheck: Disactive "Always true errors" being marked as FPs, e.g. DUPLICATE_LABEL

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#237]
A "duplicate label" erros cannot be a FP. The [site](http://tm.teresco.org/devel/datacheck.php) should not offer a "FP Entry to Submit"

btw: I've checked https://github.com/TravelMapping/HighwayData/blob/master/datacheckfps.csv, there is (currently) no DUPLICATE_LABEL entry.

**Comment by yakra** [comment]
Seconded.

> The site should not offer a "FP Entry to Submit"

I'd go a step beyond that: Not only should the "FP Entry to Submit" column be blank, but if a contributor manages to cobble together & submit an FP entry anyway, it should not be processed & added to the list of FPs; it should be added to *unmatchedfps.log* instead.

Same for LABEL_INVALID_CHAR errors.

DUPLICATE_LABEL & LABEL_INVALID_CHAR errors cannot be FPs because they break stuff.
A few other error types don't break things, but are against labelling and style guidelines, and should probably also be regarded as "Always a true error", as Tim called them on the [CHM datacheck](http://cmap.m-plex.com/tools/datacheck.php) page:
LABEL_SLASHES
LONG_UNDERSCORE
NONTERMINAL_UNDERSCO
Disallowing these types from being marked as FPs would be a good step towards "enforcing" proper labelling and style.

**Comment by michihdeu** [comment]
I absoluteley agree 👍

**Comment by jteresco** [comment]
Moved to https://github.com/TravelMapping/DataProcessing/issues/64
