### ISSUE TITLE
Header missing in HB

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#269]
If I'm not mistaken, the header has recently been removed in HB. I guess it wasn't intended.
Anyhow, it's not consistent with the rest of the site.

The footer also missing there but already for a long time, see #107

**Comment by jteresco** [comment]
I don't think this is new and was intentional for the HB route display (when a map is up) to maximize screen space dedicated to the map.  I believe I just kept it consistent for the HB pages which view lists of systems and list of routes in a system for simplicity.  I'd like to keep it as is, but would look into adding it in for all but the route map display if there's a big demand for it.

**Comment by michihdeu** [comment]
No, it's fine.
