### ISSUE TITLE
CHM-style map drawing

### ISSUE THREAD

**Issue by ssoworld** [TravelMapping/Web#29]
per http://www.aaroads.com/forum/index.php?topic=17184.msg2117290#msg2117290 - short story - sat dormant for 6 months. What's the priority on this?

**Comment by jteresco** [comment]
Curious if anyone still has interest in the CHM-style maps.  I have little motivation to implement.

**Comment by michihdeu** [comment]
I cannot remember that anyone asked for this feature and I think that the "blank" map is close to it but without borders...

**Comment by yakra** [comment]
I have little interest in CHM-style maps. The Blank map gets the same look & feel down, with the added benefit of being interactive. All that's missing are the borders and water boundaries, which aren't a priority for me personally.

**Comment by jteresco** [comment]
This reminds me to figure out how to get blank maps with Leaflet.  But that's a separate issue.  I am going to assume the CHM-style maps are not coming to the top of anyone's priority list any time soon so I'm closing.

**Comment by yakra** [comment]
@ssoworld, the code has changed a little bit since you last looked at it: :)
https://github.com/yakra/tmtools/tree/master/canvas

Most notably, you're no longer required (although it's still allowed as an option) to create a custom CSV of the routes you want to include. Instead, the program requires a clone of the HighwayData repository on disk, and gets its info from there. Use `-rg`, `--Region`, `-sys`, `--System` and other options to specify what to include.

I haven't written any documentation yet; I've been too busy crunching the code up till now. *RSN!*
Hopefully `canvas --help` will point you in the right direction.

C++11 support is required. With GCC, I use the commandline `g++ canvas.cpp -o canvas -std=c++11`

For boundaries to work, https://github.com/TravelMapping/HighwayData/pull/2024 will have to be merged.
