### ISSUE TITLE
Shields not displaying

### ISSUE THREAD

**Issue by Thing342** [TravelMapping/Web#32]
Shields are not displaying, only displaying alt text. Going to /shield/index.php returns nothing.

**Comment by Thing342** [comment]
Issue caused by a change in shield-generating syntax. The version currently live on the site displays the shield in <img> tags, which was determined to be the cause of #28. Now, they're produced as svg using the generate() function in shields/index.php. As a result of this change, the now-conflicting r= param was changed to shield=.

**Comment by Thing342** [comment]
Mostly fixed in latest pull request, however I forgot to add the caching directory, leaving errors everywhere.

**Comment by jteresco** [comment]
From @ovoss on our new (not yet public) forum:

Here's the error messages I'm getting, when I try to display my travels on one route (in this case, US 129 in Georgia). I guess due to the fatal error noted below, the map does not display:

Warning: include(/home/www/shields/index.php): failed to open stream: No such file or directory in /home/www/tm/devel/hb.php on line 2

Warning: include(): Failed opening '/home/www/shields/index.php' for inclusion (include_path='.:/usr/local/share/pear') in /home/www/tm/devel/hb.php on line 2
oscar-Home-Highway Browser
Travel Mapping Highway Browser (Draft)


Fatal error: Call to undefined function generate() in /home/www/tm/devel/hb.php on line 248

**Comment by jteresco** [comment]
My comment on it: there is no /home/www/shields directory, they'd be in /home/www/tm/shields.  So that's a place to start.

**Comment by Thing342** [comment]
Weird, as I haven't been getting that error, either in my development stack or from using the website. It would seem that $_SERVER['DOCUMENT ROOT'] is pointing to /home/www/ instead of /home/www/tm, but I haven't been able to reproduce the problem. I've just been getting warnings that it couldn't write to the cache because the directory didn't exist.

**Comment by jteresco** [comment]
Some of the trouble could be from people accessing using old URLs with http://www.teresco.org/~terescoj/travelmapping.  Those would show up as having /home/www/ as the server root.  Maybe it's time for those old URLs to go away.

**Comment by jteresco** [comment]
An error I'm seeing:

Warning: mkdir(): Permission denied in /home/www/tm/shields/index.php on line 127

Warning: file_put_contents(/home/www/tm/shields/cache/shield_nd.nd200.svg): failed to open stream: No such file or directory in /home/www/tm/shields/index.php on line 129

Which makes sense, because there is no /home/www/tm/shields/cache directory and the web server doesn't have write access to anything under /home/www/tm (nor should it, right?).

**Comment by Thing342** [comment]
Yeah, I'm seeing a lot of broken links from the old URL.

**Comment by yakra** [comment]
FWIW:
http://tm.teresco.org/devel/hb.php?r=nj.nj070
**Warning:** file_put_contents(/home/www/tm/shields/cache/shield_nj.nj070.svg): failed to open stream: Permission denied in **/home/www/tm/shields/index.php** on line **129**

**Comment by jteresco** [comment]
As far as I can tell, this issue is resolved.  The svg images seem to be cached properly and I haven't heard any reports of continued trouble.  Closing.
