### ISSUE TITLE
HB: Non-ascii character of "Val-d’Oise"

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#329]
http://travelmapping.net/hb/?u=michih&r=fraidf.d014295

Non-Ascii is not allowed in list name - I need to change it - but it should be displayed correct below the shield. However, it's displayed: "Val-d�" instead of "Val-d’Oise".

**Comment by yakra** [comment]
This could be due to the 6-character (6-byte, I presume?) [limit in the DB](https://github.com/TravelMapping/DataProcessing/issues/56) banner field. `Val-d` is 5 characters, and we may be left with half of a multi-byte character.

The topic of fixing all these banner field entries in FRA, I'd punt off to the forum topic.

Checking the appropriate DB fields for non-ascii characters could be a Good Thing.

**Comment by jteresco** [comment]
Yes, it's just cut off in the DB:

<pre>
travmap@localhost [TravelMapping]> select * from routes where root='fraidf.d014295';
+------------+---------+-------+--------+--------+------+----------------+-----------+-----------+----------+
| systemName | region  | route | banner | abbrev | city | root           | mileage   | rootOrder | csvOrder |
+------------+---------+-------+--------+--------+------+----------------+-----------+-----------+----------+
| fraidfd    | FRA-IDF | D142  | Val-d? |        |      | fraidf.d014295 | 0.0809243 |         0 |    49640 |
+------------+---------+-------+--------+--------+------+----------------+-----------+-----------+----------+
1 row in set (0.00 sec)
</pre>

This should be addressed in the site update. https://github.com/TravelMapping/DataProcessing/issues/56
