### ISSUE TITLE
ferry labels

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#354]
Some practices for handling waypoint labels for ferries developed during CHM that were never encoded in [the manual](http://travelmapping.net/devel/manual/wayptlabels.php).

"Ferry" would be right out, as that violates the standard for truncating names.
Otherwise, we tend to use the name of the ferry (line) itself, if known, or sometimes, also the ferry *terminal* if it has a name, I think? (Can anyone provide any examples of the latter?)
Otherwise truncating as we would a road name, with `Fry` taking the place of the "road type" portion of the label.

Relevant forum threads:
http://forum.travelmapping.net/index.php?topic=3219
http://forum.travelmapping.net/index.php?topic=3220

**Comment by michihdeu** [comment]
Ferry is clearly not legal since it has 5 characters. `Fry` should be it.

The only question is whether `<Departure location name>` + `<Destination location name>` + `Fry` is required if there is only a direct connection and whether plain `Fry` or `<Departure location name>` + `Fry` should be it in case of more than one service. The name of the ferry service is a No-Go for me since it could change every now and then, and - in Europe - there are many examples with different services using the very same route.

I don't see anything disputed on the forum (in the two threads linked in the OP and I don't remember other discussion).

@yakra If I don't see any objection, I'll open a poll.

**Comment by michihdeu** [comment]
Poll started: https://forum.travelmapping.net/index.php?topic=3688

**Comment by michihdeu** [comment]
https://travelmapping.net/devel/manual/wayptlabels.php#ferry
