### ISSUE TITLE
clarification on city suffixes

### ISSUE THREAD

**Issue by yakra** [TravelMapping/Web#355]
http://travelmapping.net/devel/manual/wayptlabels.php
> The 3-letter suffix should be the *first* 3 letters of the town name.

Things eventually got less strict on this, without making it into the manual.
Fort Kent vs. Fort Fairfield
New Iberia vs. New Lenox
South Portland vs. Southport
requires a workaround, so common short words such as these were allowed one or two letter abbreviations. FtK, FtF, NIb, NLe, SPo...

**Comment by michihdeu** [comment]
Please refer to https://github.com/TravelMapping/DataProcessing/issues/250 for comments. Copy:

> > Not keeping 4-letter words as we would when truncating road names.
>
> @si404 keeps 4-letter words though. Why should we go a different way for road names and "suffix" town names?
> If there are no road names, we would also use town names, e.g.:
> 
> The rule says:
> `AbcRd_Yor` instead of `AbcRd_York`
> If there is no road name it would be:
> `York`
> Odd!
> 
> > I propose also flagging 4-character suffixes not ending in `[NEWS]`.
> 
> Sorry, I don't get it. What do you mean? Flagging the above mentioned case as data error?

**Comment by michihdeu** [comment]
I always omit common words in Europe, e.g. using Bad Segeberg, Bad Kissingen or Bad Neustadt in town suffix is just `_Seg`, `_Kis` or `_Neu` instead of `_BSeg`, `_BKis` or `_BNeu`. Same for Saint-Étienne, Saint-Tropez or Saint-Denis which are just `_Eti`, `_Tro` or `_Den`.

But just because of the 3-letter town suffix rule which would end up with `_Bad`, `_Bad` and `_Bad` or `_Sai`, `_Sai` and `_Sai`.

I'm open for your proposal and suffixes like `_BSeg`

**Comment by yakra** [comment]
7Forgot to mention in the the OP: this is geared as much toward city abbrevs (as in system CSV files) as abbreviations in labels. I believe it was in this context that I originally asked Tim about creating abbrevs for "New Fooville", "Old Bartown", and the like.

> I always omit common words in Europe, e.g. using Bad Segeberg, Bad Kissingen or Bad Neustadt in town suffix is just `_Seg`, `_Kis` or `_Neu` instead of `_BSeg`, `_BKis` or `_BNeu`. Same for Saint-Étienne, Saint-Tropez or Saint-Denis which are just `_Eti`, `_Tro` or `_Den`.

Interesting. I'm not gonna come out and start yelling "Don't do it that way!". :)
Do you do the same in system CSVs? Or handle that a bit differently?

> But just because of the 3-letter town suffix rule which would end up with `_Bad`, `_Bad` and `_Bad` or `_Sai`, `_Sai` and `_Sai`.

Right. This is why Tim approved shorter abbrevs in limited cases, as noted above.
I might have just asked him pre-emptively -- ISTR having Texas on my mind when I brought it up, but don't really see anything in usausb.csv that would have been a result of that discussion.
A typical example nonetheless: `usausb;TX;US287;Bus;FtW;Fort Worth, TX;tx.us287busftw;`

> I'm open for your proposal and suffixes like `_BSeg`

Less my proposal and more something Tim OKed that didn't get explicitly codified in the manual.
To emphasize/clarify, these should still remain 3 letter suffixes, like `_BSe`. Especially in the context of city abbrevs, where the database only stores 3 characters.

**Comment by michihdeu** [comment]
> Do you do the same in system CSVs? 

yes

**Comment by michihdeu** [comment]
@yakra please rename the title and add "of wp labels" to make cleat that it's not about route city names in csv files. Thanks.

**Comment by michihdeu** [comment]
Direct link: http://travelmapping.net/devel/manual/wayptlabels.php#over2

**Comment by michihdeu** [comment]
@yakra what do you suggest?

`The 3-letter suffix should be the first 3 letters of the town name.`
-->
`The 3-letter suffix should be the first 3 letters of the town name or a short with 3 letters.`

And:

`(_PitS and _PitN for southern and northern junctions near Pittston)`

-->

`(_PitS and _PitN for southern and northern junctions near Pittston or _FtKN and _FtKS for southern and northern junctions near Fort Kent)`

And:

```
US25:
US90_A
US90_B
US90_C


US95:
NV57_Ren
NV57_Tah
NV88_PitS
NV88_PitN
```

-->

```
US90_A
US90_B
US90_C

NV57_Ren
NV57_Tah
NV88_PitS
NV88_PitN
ME161_FtKS
ME161_FtKN
```

I've removed the route example since this might change and it's not provided the line before and after in the manual.

**Comment by michihdeu** [comment]
I've already prepared the text for a poll to ask people in advance.

**Comment by michihdeu** [comment]
@yakra could you please have a quick look on this. Just to make sure that I got it right. I'd like to start a poll on the forum afterwards. Thanks.

**Comment by michihdeu** [comment]
I've suggested a different text: http://forum.travelmapping.net/index.php?topic=3645
