### ISSUE TITLE
Segments are displayed in the wrong order if rte parameter is used in url

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#40]
More info from @rickmastfan67: http://tm.teresco.org/forum/index.php?topic=50.msg225#msg225

> I-74 is in pretty bad shape as it's going in 'alphabetical' order. :(  Maybe we need to create special CSV files for that

**Comment by mapcat** [comment]
This is related to the "View Associated Routes" feature.

Related: the percentages in the table that it produces are off by two decimal places.

**Comment by jteresco** [comment]
This is a really old one.  Still an issue?

**Comment by mapcat** [comment]
It is if you think they should follow some sort of logical order. The order for the segments in the US59 list are DUMMY (why is that there?), MN, TX, KS, IA, OK, AR, MO, then 11 business routes in seemingly random order (one OK business route surrounded by 10 TX business routes). Not ordered alphabetically, or by length, or by geography, or by % completed, or by any other factor I can think of.

http://tm.teresco.org/user/mapview.php?units=miles&u=mapcat&rte=US59

The percentages are correct now.

**Comment by jteresco** [comment]
I think it's improved slightly on the tml.teresco.org version since I had to get into that code some to get things to plot on the map with lower numbered tiers drawn on top.  The only sorting beyond tier appears to be by "route" which are all identical for the above query.  The information is not currently in the DB to order segments by their order on the actual route.  It would be easy to order the business/bypass/truck routes by city (alphabetically).

**Comment by yakra** [comment]
How about sorting by Root? Sure, it's not perfect "CSV order", but a step above identical **Route**s all jumbled together, and should be easily implemented with the info already in the DB. (Right?)

**Comment by mapcat** [comment]
Looks good.

**Comment by yakra** [comment]
Some scattered thoughts, possibly better off split off into their own issue...
This shouldn't really affect when the rte= parameter is used, as most of the time one rte won't be in multiple same-tier different-color systems. But it might be good for sorting things in mapview overall.
Instead of sorting just by Tier->Root, maybe expand to Tier->[Color](https://github.com/TravelMapping/Web/issues/198#issuecomment-323563848)->Root. The thinking here is due to things like https://github.com/TravelMapping/Web/issues/198#issuecomment-322986443 and https://github.com/TravelMapping/Web/issues/198#issuecomment-323846152.
Of course, I presume sorting by color alphabetically is what would happen, which would be insufficient. 
What I've done for *tmtools* is create a numeric "SubTier" value based on color.

https://github.com/yakra/tmtools/blob/619b72020b723c5b41ce311f7ffafa2dfaca2d7c/lib/tmsystem.cpp#L121-L134

The idea is to eventually use this as a criterion for route list sorting, via overloading the < operator:

https://github.com/yakra/tmtools/blob/619b72020b723c5b41ce311f7ffafa2dfaca2d7c/lib/tmsystem.cpp#L45-L50

**Comment by jteresco** [comment]
I think this is good now.  @yakra if there are items from your most recent comment here, probably best to open a new issue for it.
