### ISSUE TITLE
clarification on city (.csv) and name (_con.csv) field usage

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#458]
http://forum.travelmapping.net/index.php?topic=3626.msg19073#msg19073

@yakra wrote:
> They (Routes) should also be named after a city they pass through, rather than a simple "Sur" & "Norte".

@neroute2 wrote
> Disagree. Sur and Norte are how they are referred to behind the scenes, and this even spills over onto some signs.

The city field is also used to indicate "official route names" in addition to route numbering, e.g. for [naca.csv](https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/naca.csv), [auta.csv](https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/auta.csv), [itaa.csv](https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/itaa.csv), [bela.csv](https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/bela.csv), and the name field of _con.csv files sometimes uses country names etc., e.g. for [eure_con.csv](https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/eure_con.csv).

From current manual (syshwylist.php):

>  **City:** The spelled-out city name for an auxiliary route or for distinguishing between pieces of the same highway in the same region. Pittsburgh for Truck US 19 (Pittsburgh). This is the text that will appear below the shield in the highway browser. Usually no text is needed except for auxiliary highways, so leave it blank (no whitespace) in most cases. The City should be spelled as the locals spell it and using international characters as needed. 

and

> **Name:** like the City field of the Chopped Routes File, the Name field is used to distinguish between otherwise identically named routes (same Route and Banner fields) or to give extra info about numberless or bannered/repeatable designations. Like the City field, this field can contain international characters.

To: Collect more examples, make a rule change suggestion to legalize the not yet covered cases and open a poll to find an agree on the change.

**Comment by michihdeu** [comment]
@si404 do you have other examples on your mind?

Or do we already want to stick with the city field usage and remove the remainders (I remember there was discussion in the past and @si404 has removed the city field entries for Spain and other countries)?

I have no issue if I had to change auta.csv and bela.csv.

**Comment by si404** [comment]
Cities are not always the best fit (for instance an island-hopping route). This Guatemalan situation is a clear example where using cities to disambiguate is less ideal and we're trying to impose an alien structure designed years ago for routes in the USA on routes not in the USA because we've been doing it for years and it's worked fine most of the time. Originally there were some files using directional suffixes to disambiguate and Tim made a rule that they had to be city names to stop the logical E/W or N/S splits being confused with directionally suffixed routes (eg I-35 in the Twin Cities) - which was a fair point. You can still see these in the alt route names in https://github.com/TravelMapping/HighwayData/blob/master/hwy_data/_systems/usaus.csv

The freeway names in the name field aren't 'illegal' - they are not forbidden, merely not formalised.

They are unnecessary unless disambiguating or expanding an abbreviated version of a name, and they bloat browser boxes when making links (which is why I got rid in my systems) if used in the city field. But they also provide useful information and 'local colour' and I don't have a problem with them being used.

Country/State names have always been the default in the name field of the _con file.

**Comment by michihdeu** [comment]
> Country/State names have always been the default in the name field of the _con file.

"like the City field" is used twice which might be misleading. And when it's "allowed" (unwritten) in `_con.csv`, I see no reason to forbid it for `.csv`.

`.csv`'s `City` field might be `used to distinguish between otherwise identically named routes`...``preferable city names (if applicable) or other common names to distinguish`. This also applies to the ` Abbreviation` field.

`.csv`'s `City` field could optionally indicate additional useful names commonly used.

`_con.csv`'s name field could use `geographical names, e.g. city names, island names or country names`.

----------------------

This is just a preliminary brainstorming but feedback is welcomed!
