### ISSUE TITLE
Manual: Data error list revision

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#479]
The [Data errors list](http://travelmapping.net/devel_new/manual/syserr.php#errors) needs to be checked that:

- [ ] All actual data errors are listed
- [ ] All descriptions are thoroughly so that our highway data managers understand how to fix the error
- [ ] The wpt editor support is indicated correct
- [ ] The FP options are indicated correct
- [ ] Not (yet) implemented data errors are commented or removed

**Comment by yakra** [comment]
> - [x] All actual data errors are listed

This is the case at this time.

> - [ ] All descriptions are thoroughly so that our highway data managers understand how to fix the error

* `HIDDEN_TERMINUS`
Hidden point at the beginning or end of a route. Routes must begin and end with visible waypoints so that users can mark all of them as traveled.
* `OUT_OF_BOUNDS`
Latitude > 90° or < -90°, or longitude > 180° or < -180°. False positives are allowed for the rare potential case of routes spanning the international date line.

> - [x] The FP options are indicated correct

All correct.

> - [x] Not (yet) implemented data errors are commented or removed

Yes, this is also the case.

- [ ] The wpt editor support is indicated correct

I believe no edits have been made to wptedit since the #374 was opened. The first column in the table in the OP, while listing short codes that are proposed for elimination entirely, still lists which which are **(actual)** ly implemented.

**Comment by michihdeu** [comment]
@yakra Please check again what I've done.

**Comment by yakra** [comment]
New changes look good.

**WPT File Editor** column:
* SHARP_ANGLE should be a YES.
* VISIBLE_HIDDEN_COLOC should be a red NO.

**Comment by michihdeu** [comment]
Of course 😞 locally fixed - closing

**Comment by yakra** [comment]
I should clarify `INVALID_FIRST_CHAR`:
Disallowed character at beginning (after any leading `*` characters) of label
