### ISSUE TITLE
Related route not found

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#494]
https://travelmapping.net/hb/index.php?r=fraara.d000963
click "related routes".
https://travelmapping.net/user/mapview.php?rte=D9 is opened and many routes displayed. However, the interrupted connected route of D9 in departement 63 is not there!

After a lot of thinking.... Since fraara.d000963 (currently) still belongs to a in-devel system, and mapview ignores in-devel routes.....

Thoughts?

**Comment by jteresco** [comment]
I am not planning to add devel routes anywhere except the highway browser.  Once the new HB to expand to connected routes is in, I think the rte= option on Mapview can probably go away.

**Comment by yakra** [comment]
And thus the Relates Routes function? :confused:

**Comment by jteresco** [comment]
The problem as we've discussed before is that the "Related Routes" aren't necessarily related at all.   They just happen to have the same "route" field in the DB.  For the HB, this would be replaced by the connected routes.

If we really want the related routes, I think we'd need to augment the data somehow to say, for example, that routes in usai, usaif, and usaib, can be related.  But that would still mean the two I-84s would be related, and they're not.  And then there's something like the I-35 situation, where you probably want all three I-35 connected routes and all 4 I-35E/W's to be related, and the latter would not be included since they have different route fields.

**Comment by michihdeu** [comment]
https://forum.travelmapping.net/index.php?topic=3697.msg19498#msg19498

**Comment by vdeane** [comment]
From a technical standpoint, it be easiest to have a "route relation ID" field or something similar.  For example, I-87 NY, I-287 NY, I-287 NJ, I-587 NY, and I-787 could all have a route relation ID of "usai-i87n" or something like that, and I-87 NC (and, in the future, I-87 VA and I-587 NC) could have something like "usai-i87s" to differentiate them.  Then related routes could just load all routes with the same route relation ID instead of relying on the route field or anything else that wouldn't match perfectly.

**Comment by jteresco** [comment]
> From a technical standpoint, it be easiest to have a "route relation ID" field or something similar. For example, I-87 NY, I-287 NY, I-287 NJ, I-587 NY, and I-787 could all have a route relation ID of "usai-i87n" or something like that, and I-87 NC (and, in the future, I-87 VA and I-587 NC) could have something like "usai-i87s" to differentiate them. Then related routes could just load all routes with the same route relation ID instead of relying on the route field or anything else that wouldn't match perfectly.

Yes, I think that's the best approach. Of course we have 60,000 routes to categorize.  I wonder how many are related to routes beyond other segments of the same connected route, then how many of those could be matched up with a mostly-automated process.  Even if most could be automated, I think there would be a significant amount of work to match up everything.

One complication on the technical side is that related routes are not necessarily part of the same system (think usai, usaib, and usaif as one example), so specification and storage might not fit seemlessly into our .csv file structure and DB design.

**Comment by jteresco** [comment]
I believe the discussion of related routes has moved elsewhere for the most part, so I am closing this.
