### ISSUE TITLE
Non-ASCII characters are not displayed correct on some pages

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#50]
For instance here: http://tm.teresco.org/shields/clinched.php?u=michih for Hungary, Romania and Denmark.

I guess there could be other pages with the same (minor) problem.
It's correct in the [HB](http://tm.teresco.org/devel/hb.php) though.

**Comment by jteresco** [comment]
This should now be fixed in the test version, which I expect will soon become the production version.

http://tmtest.teresco.org/shields/clinched.php?u=michih

Closing the issue.  Please report any other places that non-ASCII characters fail to display.  I would just need to add a line to that page to indicate UTF-8.
