### ISSUE TITLE
6 field list entry for beltways across state lines

### ISSUE THREAD

**Issue by ssoworld** [TravelMapping/Web#537]
i.e. Kansas City I-435 with entry ```KS I-435 KS/MO MO I-435 KS/MO``` but it only filled the east side.

https://travelmapping.net/hb/showroute.php?units=miles&u=master_son&r=ks.i435&cr

**Comment by yakra** [comment]
Transferred from DataProcessing to Web.

This happens because the ConnectedRoute as displayed in the HB doesn't match the ConnectedRoute as stored internally by the siteupdate program. The line in master_son.list *looks* right according to how the ConnectedRoute is displayed in the HB, but the HB (and thus the .list tool) provides the wrong info.

The [chopped](https://travelmapping.net/hb/showroute.php?units=miles&u=master_son&r=ks.i435) [routes](https://travelmapping.net/hb/showroute.php?units=miles&u=master_son&r=mo.i435) are both listed clockwise. The [ConnectedRoute](https://travelmapping.net/hb/showroute.php?units=miles&u=master_son&r=ks.i435&cr) is shown in the HB counter-clockwise.

**DataProcessing:**
I'll go more in-depth here, since I wrote this code.
Neither chopped route has its point order reversed internally. Since there are only two chopped routes in the ConnectedRoute, for both to have their point order flipped, [this](https://github.com/TravelMapping/DataProcessing/blob/35e580f8fe6a16ec6853610dfb16c60a7b99f31f/siteupdate/python-teresco/siteupdate.py#L2895-L2896) [code](https://github.com/TravelMapping/DataProcessing/blob/35e580f8fe6a16ec6853610dfb16c60a7b99f31f/siteupdate/cplusplus/siteupdate.cpp#L412-L413) would have to be executed. This never happens because `r.con_beg()`  and `q.con_end()` have the [same](https://github.com/TravelMapping/DataProcessing/blob/35e580f8fe6a16ec6853610dfb16c60a7b99f31f/siteupdate/python-teresco/siteupdate.py#L2889) [coords](https://github.com/TravelMapping/DataProcessing/blob/35e580f8fe6a16ec6853610dfb16c60a7b99f31f/siteupdate/cplusplus/siteupdate.cpp#L397).
Thus neither route is flipped, and the ConnectedRoute runs clockwise, from [the beginning of the first chopped route]( https://travelmapping.net/hb/showroute.php?r=ks.i435&lat=38.936913&lon=-94.607948&zoom=19 ) to [the end of the second/final chopped route](https://travelmapping.net/hb/showroute.php?units=miles&u=master_son&r=mo.i435). Its endpoints are really the two `MO/KS` points, not the two `KS/MO` points at the other ends of the chopped routes (as shown in the HB).
I created master_son2.list on lab2, and replaced the line in question with
`KS I-435 MO/KS MO I-435 MO/KS  # POTENTIAL BREAK - beltways`.
This behaved as expected, marking the entire route as traveled.
The line currently in master_son.list starts and ends at a single point (`KS/MO`) mid-route, and thus marks nothing as traveled.
What we *do* see marked as traveled at the link in the OP is detected concurrencies with US50 & US71.

@jteresco, what causes the HB to reverse both chopped routes' points in ConnectedRoute mode?

**Comment by jteresco** [comment]
Looks like I have an if..else if..else if..else that reverses unnecessarily exactly in this case: a 2-state beltway.  I changed the order of the checks so instead of reversing both, it reverses neither.  It's on the production site now.  Let's see if that takes care of things.

**Comment by jteresco** [comment]
I'm not coming up with another example to test this.  The other complete loop beltways in the US that I can think of are either all in one state or are in 3 (I-275 Cincinnati, I-495 DC).

**Comment by yakra** [comment]
This sounds good, and basically matches what I'm doing on the DataProcessing side.
Other 2-region loops should likewise work out fine. I found [one more example](https://travelmapping.net/hb/showroute.php?r=deubb.a010&cr), which also looks good in the new HB.

I sort of wonder how the HB would handle cases where point coords mismatch at a border. But GIGO -- these cases will be flagged DISCONNECTED_ROUTE and must be fixed at the HighwayData level.
