### ISSUE TITLE
hunm shields are broken

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/Web#615]
https://travelmapping.net/hb/showroute.php?r=hun.m001
https://travelmapping.net/hb/showroute.php?r=hun.m044

It seems that there are 5 spaces behind the number!?

**Comment by jteresco** [comment]
No ideas after a first look.  The svg template should replace the ***NUMBER*** with route number like "M1".  The svg inline I see in the showroute page looks fine...

**Comment by michihdeu** [comment]
You can click into the number and mark it. [AUT A1](https://travelmapping.net/hb/showroute.php?r=aut.a001) marks "A1" but [HUN M1](https://travelmapping.net/hb/showroute.php?r=hun.m001) marks "M1
   " including line break!

**Comment by michihdeu** [comment]
https://github.com/TravelMapping/Web/blob/d769b847ac487809a69721d04089f7d965aa8c11/shields/shieldgen.php#L231-L233

[BEL B401](https://travelmapping.net/hb/showroute.php?r=bel.b401) "B401
 " does also have a line break but the shield still looks good. [LVA A1](https://travelmapping.net/hb/showroute.php?r=lva.a001) is fine with "A1".

The problem must be caused by the svg files - or system csv files?

**Comment by jteresco** [comment]
I think I'm going to need some help from someone who understands SVG files better than I do here.  I'm not seeing why it works in some situations but not others, since the SVG files are very similar.

**Comment by jteresco** [comment]
Looking at https://forum.travelmapping.net/index.php?topic=288.msg22374#msg22374 it seems the fix was not much of a fix.  This is a strange one, as it seems the mechanism for placing the text in these shields is very similar to what we do in many other cases and we don't see the odd behavior there.  It might be better to revert the problematic shields back to generic until someone can figure out what's going on.

**Comment by michihdeu** [comment]
Fixed with the changes last May. Thanks!
