### ISSUE TITLE
Overall rankings show "TBD"

### ISSUE THREAD

**Issue by wjorda** [TravelMapping/Web#91]
The rankings on the main user page currently show "TBD" instead of an actual ranking.This may require some work over on the TravelMapping/DataProcessing front.

**Comment by Thing342** [comment]
FYI: doing this only from the web side results in massive queries that take awhile to process.

**Comment by ssoworld** [comment]
I should not be.  I would have it done during the update since the pages should just fetch the info and that’s it.

**Comment by jteresco** [comment]
This kind of information should be in the DB.  I'll plan to add it next time I'm in the code.  What kinds of rankings will we want that would be displayed enough that it's worth computing in the site update and storing in the DB, what what might we want that won't be displayed often (I'm thinking something like rankings of travels on an individual route) that would be OK to compute even if it's a little more expensive of a query?

**Comment by Thing342** [comment]
I was thinking of doing three tables: an overall stats table, with totals for routes driven, clinched, and miles driven for each user, along with a percentage and site-wide ranking for each. Then, you could have a userStatsByRegion (or an update to clinchedMileageByRegion) and userStatsBySystem tables that would show similar stats by system and by region.

I think we should move this discussion over to DataProcessing.

**Comment by yakra** [comment]
Doesn't seem to me this should matter *too* much, at least in the case of a "Distance Traveled" ranking; we already use a query to get that very same info on http://travelmapping.net/stat.php

**Comment by yakra** [comment]
Rankings implemented on /user/index2.php on lab2.

**Comment by yakra** [comment]
@Thing342 [wrote](https://github.com/TravelMapping/Web/issues/91#issuecomment-231593466):
> FYI: doing this only from the web side results in massive queries that take awhile to process. I think we should consider some sort of rankings table in the database.

I see what you mean. The query I'm using takes 1.3s, compared with 0.16s for the next slowest I saw, with everything else < 0.1s.
Double that, for one active & one active+preview query, and ouch.

I'll leave this on lab2, and maybe even make a commit to a separate branch, but not open a pull request just yet.

**Comment by jteresco** [comment]
I obviously haven't added the ranking info to the DB even though I mentioned I would 3 years ago now.  But it definitely seems that that's the way to go with this.

**Comment by yakra** [comment]
routes by region
routes by region + system

connected routes by system

active / active+preview
traveled / clinched

**Comment by jteresco** [comment]
Having these in the DB would probably make some of those "top 25" list type things for #66 easier.

**Comment by yakra** [comment]
*Thinking out loud...*
I'm still very new to SQL, and probably talking out of my hoop at least a little bit.

Started brainstorming (see above); no code yet.
What I was thinking was, new tables listing raw traveled/clinched counts per traveler/region/system.
That would be considerably faster than
https://github.com/TravelMapping/Web/blob/9ce70eae002b9e0a9d4de6b38fe64be3b893ca59/user/index.php#L126
and
https://github.com/TravelMapping/Web/blob/9ce70eae002b9e0a9d4de6b38fe64be3b893ca59/user/index.php#L142
the massive queries taking up the bulk of our time.
That would be good for getting our rankings quickly, but not much help for "Top Stats" style tables, where we'd still want to know what the individual routes are. We're back to using the `clinchedRoutes` & `clinchedConnectedRoutes` tables...
Playing around with these queries, the bulk of the time seems to come from the LEFT JOINs.

We can improve on the existing query a bit, by selecting directly from `clinchedConnectedRoutes`, as we don't use the data in `connectedRoutes`.
```PHP
SELECT COUNT(ccr.route) AS driven, SUM(ccr.clinched) AS clinched, ROUND(COUNT(ccr.route) / ".$activeRoutes." * 100,2) AS drivenPercent, ROUND(SUM(ccr.clinched) / ".$activeRoutes." * 100,2) AS clinchedPercent FROM clinchedConnectedRoutes AS ccr LEFT JOIN routes ON ccr.route = routes.root LEFT JOIN systems ON routes.systemName = systems.systemName WHERE systems.level = 'active' AND traveler = '" . $tmuser . "';
```
This eliminates one LEFT JOIN. On lab2, we're down to ~0.59s from ~0.66s. The difference becomes more significant if we select and order by `traveler`. The remaining two LEFT JOINs are necessary: level comes from system; systemname comes from routes.
Including a system column in `clinchedConnectedRoutes` could save us the more costly LEFT JOIN, and also be beneficial for system.php. Leaving the `LEFT JOIN systems` in place would hopefully not be too big a hit, with far fewer rows.
Would it be useful for Top 10 / Top 25 style lists though?

Back to the initial idea of tables of raw route counts... computing rankings during siteupdate & storing in the DB will save us from having to do 2 separate queries for Active & Active+Preview. As @ssoworld  said, "have it done during the [site] update since the pages should just fetch the info and that’s it."

---

Finally catching up with @Thing342's comment [above](https://github.com/TravelMapping/Web/issues/91#issuecomment-231749564)...

> I was thinking of doing three tables:

* > you could have a userStatsByRegion (or an update to clinchedMileageByRegion)

  - I like the idea of an update to `clinchedOverallMileageByRegion`. Possibly with the name change, to better acknowledge its expanded scope. This could take care of our chopped routes counts & ranks, Active & Active+Preview, for region.php.
  - An update to `clinchedSystemMileageByRegion` would take care of chopped routes for system.php when a region is specified.

* > and userStatsBySystem tables that would show similar stats by system and by region.

Mileage and connected routes for system.php when no region is specified.

These enhancements to existing tables still leave us without a super-easy way to get overall stats info.
We could add together all systems from the proposed `userStatsBySystem` table to get our connected route totals, but would still have to make four queries to order & run `tm_fetch_user_row_with_rank`: active driven, active clinched, active+preview driven, active+preview clinched. Thus

* > an overall stats table, with totals for routes driven, clinched, and miles driven for each user, along with a percentage and site-wide ranking for each.

This table still sounds worthwhile.

**Comment by jteresco** [comment]
The topstats are working and the queries there are fast enough not to be noticeable.  So any worries about including those in the plans for DB enhancements to make the "TBD" rankings easy to get can be put aside.

**Comment by yakra** [comment]
How about the Overall Stats table on https://travelmapping.net/user/index.php ?
How doable is this; how fast?
I have an implementation on lab2 using the RANK function in MySQL 8.0. Never merged it because it's no good for the main site & MySQL 5.7.

**Comment by jteresco** [comment]
I don't think it's too bad, but I haven't looked much..

**Comment by jteresco** [comment]
@yakra is that RANK function implementation still handy?  Looks like MariaDB supports it.

**Comment by yakra** [comment]
6c42e1f12c5eef80369e044dc3f970941f0603c5.
Beware, though...
* At 4.5 years old, the surrounding code may have changed
* the parent commit changes updateserver.sh

---

In a similar vein though off-topic for this issue, there were the changes in #325 reverted in #332

**Comment by jteresco** [comment]
Thanks - I experimented a bit last night and I have a query that works, it just is likely to slow down loading of user pages by a factor of about 20.  I think I can do better without site update/DB changes, but that might still be the way to go to make those rankings efficient.

**Comment by yakra** [comment]
Does the query differ much from the ones in 6c42e1f12c5eef80369e044dc3f970941f0603c5?
How does those compare in terms of time? It's been forever since I've played around with SQL queries.

**Comment by jteresco** [comment]
A version is on https://tmstage.teresco.org for testing.  It's slow.

> Does the query differ much from the ones in [6c42e1f](https://github.com/TravelMapping/Web/commit/6c42e1f12c5eef80369e044dc3f970941f0603c5)? How does those compare in terms of time? It's been forever since I've played around with SQL queries.

It's similar in approach.

**Comment by jteresco** [comment]
7 years and 11 months after it was opened, I can finally close this!

Credit to ChatGPT 3.5 for helping me get the new SQL correct to do this accurately and efficiently.
